# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPwiBZ1UntuX0NIpjzQGgfpItWY9qLsd
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()
a = list(uploaded.keys())[0]
df=pd.read_csv(a)
df.head(20)

df.iloc[1:20,0:4]

filtered_df=df.iloc[5:60][['Company','City','Country']]
filtered_df.head()

# prompt: # find the rows of 7th,18th,25th,38th

rows_to_display = [7, 10, 25, 38]
df.iloc[rows_to_display]

df.isnull()

# importing the module
import pandas as pd

# creating a sample dataframe
data = pd.DataFrame({
    'Brand': ['Maruti', 'Hyundai', 'Tata', 'Mahindra', 'Maruti',
              'Hyundai', 'Renault', 'Tata', 'Maruti'],
    'Year': [2012, 2014, 2011, 2015, 2012, 2016, 2014, 2018, 2019],
    'Kms Driven': [50000, 30000, 60000, 25000, 10000, 46000, 15000, 12000, 31000],
    'City': ['Gurgaon', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Chennai', 'Ghaziabad'],
    'Mileage': [28, 27, 25, 26, 28, 29, 24, 21, 24]
})

# displaying the DataFrame
display(data)

dict1 ={'Customer_id': [1,2,3,4,5,6],'Product': ['Oven','Oven','Oven','Television','Television','Television']}
df1=pd.DataFrame(dict1)
df1

dict1 ={'Customer_id': [2,4,6,8],'State': ['California','California','Texas','Hell']}
df2=pd.DataFrame(dict1)
df2

left_join_df=pd.merge(df1,df2,on='Customer_id',how='left')
left_join_df

inner_join_df=pd.merge(df1,df2,on='Customer_id',how='inner')
inner_join_df

outer_join_df=pd.merge(df1,df2,on='Customer_id',how='outer')
outer_join_df

right_join_df=pd.merge(df1,df2,on='Customer_id',how='right')
right_join_df

import numpy as np
 arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
 print(arr)
 print(arr[1,1,2])

import pandas as pd

data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32]}


data2 = {'key': ['K1', 'K2', 'K3', 'K4'],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannauj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}


df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)

print(df, "\n\n", df1)

import pandas as pd
import numpy as np
# creating a sample dataframe
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
'Mahindra', 'Maruti', 'Hyundai',
'Renault', 'Tata', 'Maruti'],
'Year': [2012, 2014, 2011, 2015, 2012,
2016, 2014, 2018, 2019],
'Kms Driven': [50000, 30000, 60000,
25000, 10000, 46000,
31000, 15000, 12000],
'City': ['Gurgaon', np.nan, 'Mumbai',
'Delhi', 'Mumbai', 'Delhi',
'Mumbai', 'Chennai', 'Ghaziabad'],
'Mileage': [28, 27, 25, 26, 28,
29, 24, 21, 24]})
# displaying the DataFrame
display(data)
#data.isnull()

import pandas as pd
sales_data = {
    'TrasactionID':[1,2,3,4,5],
    'CustomerID':[101,102,103,104,101],
    'Amount':[250,300,400,500,600],
    'Date':['2025-01-01','2025-01-02','2025-01-03','2025-01-04','2025-01-05']
}
sales_df=pd.DataFrame(sales_data)
sales_df

import numpy as np
array = np.arange(40).reshape(4,10)
print(array)

import numpy as np
array = np.arange(40).reshape(4,10)
print(array)
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr[2]+arr[7])

import numpy as np
arr = np.array([1,2,3,4,5,6,7,])
print(arr[-3:-1])

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr[1:5:2])

import pandas as pd
import numpy as np
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
'Mahindra', 'Maruti', 'Hyundai',
'Renault', 'Tata', 'Maruti'],
'Year': [2012, 2014, 2011, 2015, 2012,
2016, 2014, 2018, 2019],
'Kms Driven': [50000, 30000, 60000,
25000, 10000, 46000,
31000, 15000, 12000],
'City': ['Gurgaon', np.nan, 'Mumbai',
'Delhi', 'Mumbai', 'Delhi',
'Mumbai', 'Chennai', 'Ghaziabad'],
'Mileage': [28, 27, 25, 26, 28,
29, 24, 21, 24]})
display(data)

display(data.loc[(data.Brand == 'Renault')&(data.Year==2014)])

import matplotlib.pyplot as plt
data = [5,7,7,8,9,10,10,10,11,12,11,11]
plt.hist(data, bins=10, edgecolor='black')
plt.xlabel('Numbers')
plt.ylabel('count')
plt.title('Histogram of Data')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
np.random.seed(55)
data = np.random.randint(9,99,1000)
plt.hist(data, bins=13, edgecolor='yellow', color='orange')
plt.xlabel('age')
plt.ylabel('Number of Patients')
plt.title('Histogram of Cancer Patients')
plt.show()

import pandas as pd
data = {
    'Age' : [25, None, 30, 35, None,4.5],
    'Height': [5.5, 6.1,5.9, None, 5.8,5.2],
    'HelmetStaus':[1,None,1,0,1,1]
}

import pandas as pd
data -{
    'Name' : ['Alice', 'Bob','Alice','Charlie','Bob' ],
    'Age' : [25, 30, 25, 35, 30],
    'City':['hyd','goa','banglore','hyd','chennai']
}
df = pd.DataFrame(data)
print('Original')

e1=['gaurav',2,5,20000,'yes']
e2=['john',3,5,23000,'yes']
e3=['mani',4,6,24000,'no']
e4=['chetan',2,5,20000,'yes']
e5=['kranthi',3,5,23000,'no']
e6=['muzzu',4,6,24000,'no']

emp_data=[e1,e2,e3,e4,e5,e6]
emp_data

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
np.random.seed(10)
data = pd.DataFrame({
    'value' : np.concatenate([np.random.normal(0, 1, 100), np.random.normal(10, 1, 10)])
})
Q1 = data['value'].quantile(0.25)
Q3 = data['value'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = data[(data['value'] < lower_bound) | (data['value'] > upper_bound)]
print(outliers)

import matplotlib.pyplot as plt
temperature = [25, 28, 32, 35, 38, 40, 42, 45, 30, 33, 36, 37]
ice_cream_sales = [200, 250, 300, 350, 400, 420, 430, 450, 280, 310, 360, 370]
plt.figure(figsize=(8, 6))
plt.scatter(temperature, ice_cream_sales, color='orange', edgecolor='black', alpha=0.8)
plt.title('Temperature vs Ice Cream Sales')
plt.xlabel('Temperature (Celsius)')
plt.ylabel('Ice Cream Sales')
plt.grid(True)
plt.show()